### ISSUE TITLE
Potential crash

### ISSUE THREAD

**Issue by mansatgigset** [pointfreeco/swift-concurrency-extras#10]
### Description

We have identified a potential crash in `iterator?.next()` that might be related to this library, with a suggested improvement, see https://github.com/apple/swift/issues/69367.

### Checklist

- [ ] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-concurrency-extras/issues) or [discussion](https://github.com/pointfreeco/swift-concurrency-extras/discussions).

### Expected behavior

No crash

### Actual behavior

Crash

### Steps to reproduce

See https://github.com/apple/swift/issues/69367

### swift-concurrency-extras version information

1.0.0

### Destination operating system

Multiple os

### Xcode version information

Version 15.0 (15A240d)

### Swift Compiler version information

```shell
swift-driver version: 1.87.1 Apple Swift version 5.9 (swiftlang-5.9.0.128.108 clang-1500.0.40.1)
Target: arm64-apple-macosx14.0
```

**Comment by stephencelis** [comment]
@mansatgigset Thanks for letting us know! Any interest in PRing the fix suggested in that thread? If not we can take care of it, no worries.

**Comment by mansatgigset** [comment]
@stephencelis As this fix should be compatible further back than what I believe OSAllocatedUnfairLock is supported, it feels better that you come up with a solution you feel confident with.

**Comment by stephencelis** [comment]
@mansatgigset I think we can use a simple `NSLock` instead :smile: Can you take it for a spin?
