### ISSUE TITLE
Small documentation "bug" in the readme examples

### ISSUE THREAD

**Issue by filiplazov** [pointfreeco/swift-concurrency-extras#4]
### Description

After trying to copy paste the code with the Number Fact model with small changes (like adding a constructor to the model), I noticed that the sample code is not 100% working without a small change

This diff here

```diff
 func testIsLoading() async {
+  await withMainSerialExecutor {
     let model = NumberFactModel(getFact: { "\($0) is a good number" })

     let task = Task { await model.getFactButtonTapped() }
     await Task.yield()
     XCTAssertEqual(model.isLoading, true)
     XCTAssertEqual(model.fact, nil)

     await task.value
     XCTAssertEqual(model.isLoading, false)
     XCTAssertEqual(model.fact, "0 is a good number.")
+  }
 }
```

The closure we inject should include an await Task.yield() as per your video
Additionally the string should end with a full stop `.` to match the assert (or other way around)

```swift
let model = NumberFactModel(getFact: {
   await Task.yield()
   return "\($0) is a good number."
})
```

### Checklist

- [X] If possible, I've reproduced the issue using the `main` branch of this package.
- [X] This issue hasn't been addressed in an [existing GitHub issue](https://github.com/pointfreeco/swift-concurrency-extras/issues) or [discussion](https://github.com/pointfreeco/swift-concurrency-extras/discussions).

**Comment by stephencelis** [comment]
@filiplazov Can you explain what is not 100% working? What's the exact issue you are seeing? Is it a particular XCTFailure?

Also, what version of Xcode/Swift/iOS are you using? We have noticed that `Task.yield` is sometimes required here, but it totally seems like it depends on the version of the Swift runtime.

**Comment by filiplazov** [comment]
I am sorry if did not provide the info.
Two asserts are failing after await Task.yield()

```swift
XCTAssertEqual(model.isLoading, true)
XCTAssertEqual(model.fact, nil)
```

> XCTAssertEqual failed: ("false") is not equal to ("true")
> XCTAssertEqual failed: ("Optional("0 is a good number.")") is not equal to ("nil")

Loading is false and the fact string already returned from the mock function

I am using Xcode 14.3.1, iOS 16.4, Swift 5.8

Here is the entire Test case file that would make those asserts fail (I commented out the extra yield)

```swift
import XCTest
@testable import XC14Concurrency
import ConcurrencyExtras

@MainActor
class NumberFactModel {
  var fact: String?
  var isLoading = false
  var number = 0

  // Inject the request dependency explicitly to make it testable, but can also
  // be provided via a dependency management library.
  let getFact: (Int) async throws -> String

  init(getFact: @escaping (Int) async throws -> String) {
    self.getFact = getFact
  }

  func getFactButtonTapped() async {
    self.isLoading = true
    defer { self.isLoading = false }
    do {
      self.fact = try await self.getFact(self.number)
    } catch {
      // TODO: Handle error
    }
  }
}

final class XC14ConcurrencyTests: XCTestCase {

  func testIsLoading() async {
    await withMainSerialExecutor {
      let model = NumberFactModel(getFact: {
        //await Task.yield()
        return "\($0) is a good number."
      })

      let task = Task { await model.getFactButtonTapped() }
      await Task.yield()
      XCTAssertEqual(model.isLoading, true)
      XCTAssertEqual(model.fact, nil)

      await task.value
      XCTAssertEqual(model.isLoading, false)
      XCTAssertEqual(model.fact, "0 is a good number.")
    }
  }
}

```

**Comment by stephencelis** [comment]
@filiplazov Can you check with the latest beta, too? I think we've been targeting Xcode 15 with our examples, though in this case making it backwards compatible might be preferable. We'll chat about it soon!

**Comment by filiplazov** [comment]
Just tested with Xcode 15 beta 5, same exact issue as the ones with Xcode 14.3.1 and Xcode 15 beta 4.
It kind of makes sense, there is nothing in the `getFact` that would simulate time passing, no asynchronous work is done and it immediately returns the string after the initial Task.yield which gives the only task time to execute fully and update the model.

**Comment by filiplazov** [comment]
Just to add, I also tried replacing the `Task.yield` inside `getFact` closure with `try! await Task.sleep(for: .milliseconds(1))` and it also works and has the same effect.

**Comment by mbrandonw** [comment]
Thanks for the report @filiplazov! We just merged a PR that should hopefully make the situation clearer.
